alias git-graph='git log --all --decorate --oneline --graph'
alias git-amend='git commit --amend'
alias git-push-with-tags='git push && git push --tags'
alias git-master='git checkout master'
alias git-develop='git checkout develop'